name: OpenWRT Build for Mikrotik via GitHub Actions
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ipq40xx, ath79, ramips-mt7621, mvebu-cortexa72, ipq806x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build firmware
      run: |
        TARGET=${{ matrix.target }} \
        OPENWRT_VERSION=v24.10.0 \
        ./build.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-${{ matrix.target }}
        path: build/${{ matrix.target }}/*.bin
        include-hidden-files: true  # Pro zahrnutí skrytých souborů

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: OpenWRT ${{ github.ref_name }}
        files: |
          **/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
